brain_swap/config/routes.rb
BrainSwap::Application.routes.draw do
  resources :sites

end

brain_swap/app/models/site.rb
class Site < ActiveRecord::Base
    validates :content, :linkws, :presence => true
    
    def self.search(search)
        if search
            find(:all, :conditions => ['content LIKE ?', "%#{search}%"])
        else
            find(:all)
        end
    end   
end

brain_swap/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

brain_swap/app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def index
    @sites = Site.all
    @saved = @sites.count(:linkcp)
    
#    if params[:search]
    @sites = Site.search(params[:search])
#        render "search"
#    else 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
#    end
    end
  end
  # GET /sites/1
  # GET /sites/1.json
  
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])
    
    # Domain Name
    re='((?:[a-z][a-z\\.\\d\\-]+)\\.(?:[a-z][a-z\\-]+))(?![\\w\\.])'	
    @m=Regexp.new(re,Regexp::IGNORECASE)
    @host = @m.match(@site.linkws)[1] 
    @site.host = @host
    
    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :ok }
    end
  end
end

brain_swap/app/helpers/application_helper.rb
module ApplicationHelper
end

brain_swap/app/helpers/sites_helper.rb
module SitesHelper
end

brain_swap/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrainSwap</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

brain_swap/app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
 <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fieldleft">
    <%= f.label "Title" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="fieldleft">
    <%= f.label "Beschreibung" %><br />
    <%= f.text_area :content, :size => "30x4"%>
  </div>
  <div class="fieldleft">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="fieldleft">
    <%= f.label "Link" %><br />
    <%= f.text_area :linkws, :size => "30x4" %>
  </div>

    <div class="clear"/>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

brain_swap/app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

brain_swap/app/views/sites/index.html.erb
<h1>Brain Swap</h1>

<%= form_tag sites_path, :method => 'get' do %>
    <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil%>
    </p>
<% end%>
<%= link_to 'New Site', new_site_path %> 
<table width="100%">
  <tr>
    <th>Datum</th>
    <th>Title</th>
    <th>Beschreibung</th>
    <th>Category</th>
    <th>Host</th>
    <th>Gesichert</th>

  </tr>

<% @sites.each do |site| %>
  <tr class="<%=cycle('rowa','rowb')%>">
    <td><%= site.created_at.strftime('%d.%m.%y - %H:%M')+" h" %></td>
    <td><%=link_to site.name, site.linkws %></td>
    <td><%= raw site.content.gsub(/#(\w*)/) { link_to("##{$1}", sites_path(:search => "bla")) }%></td>
    <td><%= site.category %></td>
    <td><%= site.host %></td>
    <% if @sites.count(:linkcp) != 0 %>
        <td><%= image_tag("CheckedIcon.jpg",:alt=>"CheckIcon", 
                                            :size=>"25x30", :border=>0)%></td>
    <% else%>
        <td><%= image_tag("ftcheckedbox.png",:alt=>"CheckIcon", 
                                             :size=>"20x20", :border=>0)%></td>
    <% end %>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

brain_swap/app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

brain_swap/app/views/sites/search.html.erb
TEST
<table width="100%">
  <tr>
    <th>Datum</th>
    <th>Title</th>
    <th>Beschreibung</th>
    <th>Category</th>
    <th>Host</th>
    <th>Gesichert</th>

  </tr>

<% @sites.each do |site| %>
  <tr class="<%=cycle('rowa','rowb')%>">
    <td><%= site.created_at.strftime('%d.%m.%y - %H:%M')+" h" %></td>
    <td><%=link_to site.name, site.linkws %></td>
    <td><%= raw site.content.gsub(/#(\w*)/) { link_to("##{$1}", "heise.de") }%></td>
    <td><%= site.category %></td>
    <td><%= site.host %></td>
    <% if @sites.count(:linkcp) != 0 %>
        <td><%= image_tag("CheckedIcon.jpg",:alt=>"CheckIcon", 
                                            :size=>"25x30", :border=>0)%></td>
    <% else%>
        <td><%= image_tag("ftcheckedbox.png",:alt=>"CheckIcon", 
                                             :size=>"20x20", :border=>0)%></td>
    <% end %>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

brain_swap/app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @site.name %>
</p>

<p>
  <b>Content:</b>
  <%= @site.content %>
</p>

<p>
  <b>Linkws:</b>
  <%= @site.linkws %>
</p>

<p>
  <b>Linkcp:</b>
  <%= @site.linkcp %>
</p>

<p>
  <b>Category:</b>
  <%= @site.category %>
</p>

<p>
  <b>Tag:</b>
  <%= @site.tag %>
</p>

<p>
  <b>Host:</b>
  <%= @site.host %>
</p>


<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>